# AUTO GENERATED FILE - DO NOT EDIT

dashGraph3D <- function(id=NULL, graphData=NULL, heightRatio=NULL, backgroundColor=NULL, width=NULL, nodeRelSize=NULL, nodeLabel=NULL, nodeLabel_attr_type=NULL, nodeLabel_attr_supertype=NULL, nodeColor=NULL, nodeColor_common_type=NULL, nodeColor_common_supertype=NULL, nodeURL=NULL, nodeURL_attr_type=NULL, nodeURL_attr_supertype=NULL, nodeAutoColorBy=NULL, nodeOpacity=NULL, nodeCanvasObjectMode=NULL, nodeThreeObject=NULL, useNodeIcon=NULL, nodeIcon=NULL, nodeIcon_attr_type=NULL, nodeIcon_attr_supertype=NULL, nodeIcon_common_type=NULL, nodeIcon_common_supertype=NULL, nodeIcon_fontsheets=NULL, useNodeImg=NULL, nodeImg=NULL, nodeImg_attr_type=NULL, nodeImg_attr_supertype=NULL, nodeImg_common_type=NULL, nodeImg_common_supertype=NULL, linkLabel=NULL, linkColor=NULL, linkColor_attr_type=NULL, linkColor_attr_supertype=NULL, linkAutoColorBy=NULL, linkOpacity=NULL, linkWidth=NULL, linkCurvature=NULL, linkThreeObject=NULL, linkThreeObjectExtend=NULL, linkCanvasObjectMode=NULL, linkDirectionalArrowLength=NULL, linkDirectionalArrowRelPos=NULL, zoomOut=NULL, center=NULL, cooldownTime=NULL, d3Force=NULL, onNodeClick=NULL, onNodeRightClick=NULL, onNodeHover=NULL, onLinkClick=NULL, onLinkRightClick=NULL, onLinkHover=NULL, onBackgroundClick=NULL, onBackgroundRightClick=NULL, interactive=NULL, enableZoomPanInteraction=NULL, enableNavigationControls=NULL, enablePointerInteraction=NULL, enableNodeDrag=NULL, nodeZoomId=NULL, nodesSelected=NULL, nodeIdsDrag=NULL, nodeRightClicked=NULL, nodeRightClickedViewpointCoordinates=NULL, linksSelected=NULL, linkIdsNodesDrag=NULL, graknStatus=NULL, maxDepth_neighbours_select=NULL, max_nodes_render=NULL, size=NULL, externalobject_source=NULL, externalobject_input=NULL, nodeHovered=NULL, centreCoordinates=NULL, graphData_changed=NULL, updated=NULL, nodeIdsHighlight=NULL, nodeIdsVisible=NULL, linkIdsFilter=NULL, useCoordinates=NULL, pixelUnitRatio=NULL, showCoordinates=NULL, gravity=NULL, focused=NULL) {
    
    props <- list(id=id, graphData=graphData, heightRatio=heightRatio, backgroundColor=backgroundColor, width=width, nodeRelSize=nodeRelSize, nodeLabel=nodeLabel, nodeLabel_attr_type=nodeLabel_attr_type, nodeLabel_attr_supertype=nodeLabel_attr_supertype, nodeColor=nodeColor, nodeColor_common_type=nodeColor_common_type, nodeColor_common_supertype=nodeColor_common_supertype, nodeURL=nodeURL, nodeURL_attr_type=nodeURL_attr_type, nodeURL_attr_supertype=nodeURL_attr_supertype, nodeAutoColorBy=nodeAutoColorBy, nodeOpacity=nodeOpacity, nodeCanvasObjectMode=nodeCanvasObjectMode, nodeThreeObject=nodeThreeObject, useNodeIcon=useNodeIcon, nodeIcon=nodeIcon, nodeIcon_attr_type=nodeIcon_attr_type, nodeIcon_attr_supertype=nodeIcon_attr_supertype, nodeIcon_common_type=nodeIcon_common_type, nodeIcon_common_supertype=nodeIcon_common_supertype, nodeIcon_fontsheets=nodeIcon_fontsheets, useNodeImg=useNodeImg, nodeImg=nodeImg, nodeImg_attr_type=nodeImg_attr_type, nodeImg_attr_supertype=nodeImg_attr_supertype, nodeImg_common_type=nodeImg_common_type, nodeImg_common_supertype=nodeImg_common_supertype, linkLabel=linkLabel, linkColor=linkColor, linkColor_attr_type=linkColor_attr_type, linkColor_attr_supertype=linkColor_attr_supertype, linkAutoColorBy=linkAutoColorBy, linkOpacity=linkOpacity, linkWidth=linkWidth, linkCurvature=linkCurvature, linkThreeObject=linkThreeObject, linkThreeObjectExtend=linkThreeObjectExtend, linkCanvasObjectMode=linkCanvasObjectMode, linkDirectionalArrowLength=linkDirectionalArrowLength, linkDirectionalArrowRelPos=linkDirectionalArrowRelPos, zoomOut=zoomOut, center=center, cooldownTime=cooldownTime, d3Force=d3Force, onNodeClick=onNodeClick, onNodeRightClick=onNodeRightClick, onNodeHover=onNodeHover, onLinkClick=onLinkClick, onLinkRightClick=onLinkRightClick, onLinkHover=onLinkHover, onBackgroundClick=onBackgroundClick, onBackgroundRightClick=onBackgroundRightClick, interactive=interactive, enableZoomPanInteraction=enableZoomPanInteraction, enableNavigationControls=enableNavigationControls, enablePointerInteraction=enablePointerInteraction, enableNodeDrag=enableNodeDrag, nodeZoomId=nodeZoomId, nodesSelected=nodesSelected, nodeIdsDrag=nodeIdsDrag, nodeRightClicked=nodeRightClicked, nodeRightClickedViewpointCoordinates=nodeRightClickedViewpointCoordinates, linksSelected=linksSelected, linkIdsNodesDrag=linkIdsNodesDrag, graknStatus=graknStatus, maxDepth_neighbours_select=maxDepth_neighbours_select, max_nodes_render=max_nodes_render, size=size, externalobject_source=externalobject_source, externalobject_input=externalobject_input, nodeHovered=nodeHovered, centreCoordinates=centreCoordinates, graphData_changed=graphData_changed, updated=updated, nodeIdsHighlight=nodeIdsHighlight, nodeIdsVisible=nodeIdsVisible, linkIdsFilter=linkIdsFilter, useCoordinates=useCoordinates, pixelUnitRatio=pixelUnitRatio, showCoordinates=showCoordinates, gravity=gravity, focused=focused)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'Graph3D',
        namespace = 'dash_react_force_graph',
        propNames = c('id', 'graphData', 'heightRatio', 'backgroundColor', 'width', 'nodeRelSize', 'nodeLabel', 'nodeLabel_attr_type', 'nodeLabel_attr_supertype', 'nodeColor', 'nodeColor_common_type', 'nodeColor_common_supertype', 'nodeURL', 'nodeURL_attr_type', 'nodeURL_attr_supertype', 'nodeAutoColorBy', 'nodeOpacity', 'nodeCanvasObjectMode', 'nodeThreeObject', 'useNodeIcon', 'nodeIcon', 'nodeIcon_attr_type', 'nodeIcon_attr_supertype', 'nodeIcon_common_type', 'nodeIcon_common_supertype', 'nodeIcon_fontsheets', 'useNodeImg', 'nodeImg', 'nodeImg_attr_type', 'nodeImg_attr_supertype', 'nodeImg_common_type', 'nodeImg_common_supertype', 'linkLabel', 'linkColor', 'linkColor_attr_type', 'linkColor_attr_supertype', 'linkAutoColorBy', 'linkOpacity', 'linkWidth', 'linkCurvature', 'linkThreeObject', 'linkThreeObjectExtend', 'linkCanvasObjectMode', 'linkDirectionalArrowLength', 'linkDirectionalArrowRelPos', 'zoomOut', 'center', 'cooldownTime', 'd3Force', 'onNodeClick', 'onNodeRightClick', 'onNodeHover', 'onLinkClick', 'onLinkRightClick', 'onLinkHover', 'onBackgroundClick', 'onBackgroundRightClick', 'interactive', 'enableZoomPanInteraction', 'enableNavigationControls', 'enablePointerInteraction', 'enableNodeDrag', 'nodeZoomId', 'nodesSelected', 'nodeIdsDrag', 'nodeRightClicked', 'nodeRightClickedViewpointCoordinates', 'linksSelected', 'linkIdsNodesDrag', 'graknStatus', 'maxDepth_neighbours_select', 'max_nodes_render', 'size', 'externalobject_source', 'externalobject_input', 'nodeHovered', 'centreCoordinates', 'graphData_changed', 'updated', 'nodeIdsHighlight', 'nodeIdsVisible', 'linkIdsFilter', 'useCoordinates', 'pixelUnitRatio', 'showCoordinates', 'gravity', 'focused'),
        package = 'dashReactForceGraph'
        )

    structure(component, class = c('dash_component', 'list'))
}
