# AUTO GENERATED FILE - DO NOT EDIT

dashGraph3D <- function(id=NULL, active=NULL, backgroundColor=NULL, cameraPosition=NULL, centerAt=NULL, centreCoordinates=NULL, controlType=NULL, cooldownTicks=NULL, cooldownTime=NULL, d3AlphaDecay=NULL, d3AlphaMin=NULL, d3ReheatSimulation=NULL, d3VelocityDecay=NULL, dagLevelDistance=NULL, dagMode=NULL, dagModeOn=NULL, dagNodeIds=NULL, emitParticle=NULL, enableNodeDrag=NULL, externalobject_input=NULL, externalobject_source=NULL, forceEngine=NULL, getGraphBbox=NULL, graphData=NULL, gravity=NULL, heightRatio=NULL, interactive=NULL, linkAutoColorBy=NULL, linkColor=NULL, linkCurvature=NULL, linkCurveRotation=NULL, linkDesc=NULL, linkDirectionalArrowColor=NULL, linkDirectionalArrowLength=NULL, linkDirectionalArrowRelPos=NULL, linkDirectionalArrowResolution=NULL, linkDirectionalParticleColor=NULL, linkDirectionalParticleResolution=NULL, linkDirectionalParticleSpeed=NULL, linkDirectionalParticleWidth=NULL, linkDirectionalParticles=NULL, linkHoverPrecision=NULL, linkId=NULL, linkIdsHighlight=NULL, linkIdsVisible=NULL, linkLabel=NULL, linkLineDash=NULL, linkOpacity=NULL, linkResolution=NULL, linkSource=NULL, linkTarget=NULL, linkWidth=NULL, maxDepth_neighbours_select=NULL, ngraphPhysics=NULL, nodeAutoColorBy=NULL, nodeColor=NULL, nodeDesc=NULL, nodeIcon=NULL, nodeIcon_fontsheets=NULL, nodeId=NULL, nodeIdsHighlight=NULL, nodeIdsVisible=NULL, nodeImg=NULL, nodeLabel=NULL, nodeOpacity=NULL, nodeRelSize=NULL, nodeResolution=NULL, nodeURL=NULL, nodeVal=NULL, nodeZoomId=NULL, nodesSelected=NULL, numDimensions=NULL, pauseAnimation=NULL, pixelUnitRatio=NULL, refresh=NULL, rendererConfig=NULL, resumeAnimation=NULL, showCoordinates=NULL, showNavInfo=NULL, size=NULL, sortRels1Descend=NULL, sortRels2Descend=NULL, sortRelsBy1=NULL, sortRelsBy2=NULL, sortRoleplayers1Descend=NULL, sortRoleplayers2Descend=NULL, sortRoleplayersBy1=NULL, sortRoleplayersBy2=NULL, useCoordinates=NULL, useNodeIcon=NULL, useNodeImg=NULL, warmupTicks=NULL, zoom=NULL, zoomToFit=NULL) {
    
    props <- list(id=id, active=active, backgroundColor=backgroundColor, cameraPosition=cameraPosition, centerAt=centerAt, centreCoordinates=centreCoordinates, controlType=controlType, cooldownTicks=cooldownTicks, cooldownTime=cooldownTime, d3AlphaDecay=d3AlphaDecay, d3AlphaMin=d3AlphaMin, d3ReheatSimulation=d3ReheatSimulation, d3VelocityDecay=d3VelocityDecay, dagLevelDistance=dagLevelDistance, dagMode=dagMode, dagModeOn=dagModeOn, dagNodeIds=dagNodeIds, emitParticle=emitParticle, enableNodeDrag=enableNodeDrag, externalobject_input=externalobject_input, externalobject_source=externalobject_source, forceEngine=forceEngine, getGraphBbox=getGraphBbox, graphData=graphData, gravity=gravity, heightRatio=heightRatio, interactive=interactive, linkAutoColorBy=linkAutoColorBy, linkColor=linkColor, linkCurvature=linkCurvature, linkCurveRotation=linkCurveRotation, linkDesc=linkDesc, linkDirectionalArrowColor=linkDirectionalArrowColor, linkDirectionalArrowLength=linkDirectionalArrowLength, linkDirectionalArrowRelPos=linkDirectionalArrowRelPos, linkDirectionalArrowResolution=linkDirectionalArrowResolution, linkDirectionalParticleColor=linkDirectionalParticleColor, linkDirectionalParticleResolution=linkDirectionalParticleResolution, linkDirectionalParticleSpeed=linkDirectionalParticleSpeed, linkDirectionalParticleWidth=linkDirectionalParticleWidth, linkDirectionalParticles=linkDirectionalParticles, linkHoverPrecision=linkHoverPrecision, linkId=linkId, linkIdsHighlight=linkIdsHighlight, linkIdsVisible=linkIdsVisible, linkLabel=linkLabel, linkLineDash=linkLineDash, linkOpacity=linkOpacity, linkResolution=linkResolution, linkSource=linkSource, linkTarget=linkTarget, linkWidth=linkWidth, maxDepth_neighbours_select=maxDepth_neighbours_select, ngraphPhysics=ngraphPhysics, nodeAutoColorBy=nodeAutoColorBy, nodeColor=nodeColor, nodeDesc=nodeDesc, nodeIcon=nodeIcon, nodeIcon_fontsheets=nodeIcon_fontsheets, nodeId=nodeId, nodeIdsHighlight=nodeIdsHighlight, nodeIdsVisible=nodeIdsVisible, nodeImg=nodeImg, nodeLabel=nodeLabel, nodeOpacity=nodeOpacity, nodeRelSize=nodeRelSize, nodeResolution=nodeResolution, nodeURL=nodeURL, nodeVal=nodeVal, nodeZoomId=nodeZoomId, nodesSelected=nodesSelected, numDimensions=numDimensions, pauseAnimation=pauseAnimation, pixelUnitRatio=pixelUnitRatio, refresh=refresh, rendererConfig=rendererConfig, resumeAnimation=resumeAnimation, showCoordinates=showCoordinates, showNavInfo=showNavInfo, size=size, sortRels1Descend=sortRels1Descend, sortRels2Descend=sortRels2Descend, sortRelsBy1=sortRelsBy1, sortRelsBy2=sortRelsBy2, sortRoleplayers1Descend=sortRoleplayers1Descend, sortRoleplayers2Descend=sortRoleplayers2Descend, sortRoleplayersBy1=sortRoleplayersBy1, sortRoleplayersBy2=sortRoleplayersBy2, useCoordinates=useCoordinates, useNodeIcon=useNodeIcon, useNodeImg=useNodeImg, warmupTicks=warmupTicks, zoom=zoom, zoomToFit=zoomToFit)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'Graph3D',
        namespace = 'dash_react_force_graph',
        propNames = c('id', 'active', 'backgroundColor', 'cameraPosition', 'centerAt', 'centreCoordinates', 'controlType', 'cooldownTicks', 'cooldownTime', 'd3AlphaDecay', 'd3AlphaMin', 'd3ReheatSimulation', 'd3VelocityDecay', 'dagLevelDistance', 'dagMode', 'dagModeOn', 'dagNodeIds', 'emitParticle', 'enableNodeDrag', 'externalobject_input', 'externalobject_source', 'forceEngine', 'getGraphBbox', 'graphData', 'gravity', 'heightRatio', 'interactive', 'linkAutoColorBy', 'linkColor', 'linkCurvature', 'linkCurveRotation', 'linkDesc', 'linkDirectionalArrowColor', 'linkDirectionalArrowLength', 'linkDirectionalArrowRelPos', 'linkDirectionalArrowResolution', 'linkDirectionalParticleColor', 'linkDirectionalParticleResolution', 'linkDirectionalParticleSpeed', 'linkDirectionalParticleWidth', 'linkDirectionalParticles', 'linkHoverPrecision', 'linkId', 'linkIdsHighlight', 'linkIdsVisible', 'linkLabel', 'linkLineDash', 'linkOpacity', 'linkResolution', 'linkSource', 'linkTarget', 'linkWidth', 'maxDepth_neighbours_select', 'ngraphPhysics', 'nodeAutoColorBy', 'nodeColor', 'nodeDesc', 'nodeIcon', 'nodeIcon_fontsheets', 'nodeId', 'nodeIdsHighlight', 'nodeIdsVisible', 'nodeImg', 'nodeLabel', 'nodeOpacity', 'nodeRelSize', 'nodeResolution', 'nodeURL', 'nodeVal', 'nodeZoomId', 'nodesSelected', 'numDimensions', 'pauseAnimation', 'pixelUnitRatio', 'refresh', 'rendererConfig', 'resumeAnimation', 'showCoordinates', 'showNavInfo', 'size', 'sortRels1Descend', 'sortRels2Descend', 'sortRelsBy1', 'sortRelsBy2', 'sortRoleplayers1Descend', 'sortRoleplayers2Descend', 'sortRoleplayersBy1', 'sortRoleplayersBy2', 'useCoordinates', 'useNodeIcon', 'useNodeImg', 'warmupTicks', 'zoom', 'zoomToFit'),
        package = 'dashReactForceGraph'
        )

    structure(component, class = c('dash_component', 'list'))
}
