# AUTO GENERATED FILE - DO NOT EDIT

dashGraph2D <- function(id=NULL, graphData=NULL, nodeId=NULL, linkSource=NULL, linkTarget=NULL, backgroundColor=NULL, showNavInfo=NULL, nodeRelSize=NULL, nodeVal=NULL, nodeLabel=NULL, nodeDesc=NULL, nodeColor=NULL, nodeAutoColorBy=NULL, nodeOpacity=NULL, nodeResolution=NULL, linkLabel=NULL, linkDesc=NULL, linkColor=NULL, linkAutoColorBy=NULL, linkOpacity=NULL, linkLineDash=NULL, linkWidth=NULL, linkResolution=NULL, linkCurvature=NULL, linkCurveRotation=NULL, linkDirectionalArrowLength=NULL, linkDirectionalArrowColor=NULL, linkDirectionalArrowRelPos=NULL, linkDirectionalArrowResolution=NULL, linkDirectionalParticles=NULL, linkDirectionalParticleSpeed=NULL, linkDirectionalParticleWidth=NULL, linkDirectionalParticleColor=NULL, linkDirectionalParticleResolution=NULL, emitParticle=NULL, rendererConfig=NULL, pauseAnimation=NULL, resumeAnimation=NULL, centerAt=NULL, zoom=NULL, zoomToFit=NULL, cameraPosition=NULL, refresh=NULL, numDimensions=NULL, forceEngine=NULL, dagMode=NULL, dagModeOn=NULL, dagLevelDistance=NULL, dagNodeIds=NULL, ngraphPhysics=NULL, warmupTicks=NULL, cooldownTicks=NULL, cooldownTime=NULL, linkHoverPrecision=NULL, controlType=NULL, enableNodeDrag=NULL, getGraphBbox=NULL, heightRatio=NULL, size=NULL, active=NULL, nodeURL=NULL, useNodeImg=NULL, nodeImg=NULL, useNodeIcon=NULL, nodeIcon=NULL, nodeIcon_fontsheets=NULL, linkId=NULL, interactive=NULL, nodeZoomId=NULL, sortRelsBy1=NULL, sortRelsBy2=NULL, sortRoleplayersBy1=NULL, sortRoleplayersBy2=NULL, sortRels1Descend=NULL, sortRels2Descend=NULL, sortRoleplayers1Descend=NULL, sortRoleplayers2Descend=NULL, nodesSelected=NULL, nodeIdsHighlight=NULL, nodeIdsVisible=NULL, linkIdsHighlight=NULL, linkIdsVisible=NULL, externalobject_source=NULL, externalobject_input=NULL, centreCoordinates=NULL, useCoordinates=NULL, pixelUnitRatio=NULL, showCoordinates=NULL, gravity=NULL, maxDepth_neighbours_select=NULL) {
    
    props <- list(id=id, graphData=graphData, nodeId=nodeId, linkSource=linkSource, linkTarget=linkTarget, backgroundColor=backgroundColor, showNavInfo=showNavInfo, nodeRelSize=nodeRelSize, nodeVal=nodeVal, nodeLabel=nodeLabel, nodeDesc=nodeDesc, nodeColor=nodeColor, nodeAutoColorBy=nodeAutoColorBy, nodeOpacity=nodeOpacity, nodeResolution=nodeResolution, linkLabel=linkLabel, linkDesc=linkDesc, linkColor=linkColor, linkAutoColorBy=linkAutoColorBy, linkOpacity=linkOpacity, linkLineDash=linkLineDash, linkWidth=linkWidth, linkResolution=linkResolution, linkCurvature=linkCurvature, linkCurveRotation=linkCurveRotation, linkDirectionalArrowLength=linkDirectionalArrowLength, linkDirectionalArrowColor=linkDirectionalArrowColor, linkDirectionalArrowRelPos=linkDirectionalArrowRelPos, linkDirectionalArrowResolution=linkDirectionalArrowResolution, linkDirectionalParticles=linkDirectionalParticles, linkDirectionalParticleSpeed=linkDirectionalParticleSpeed, linkDirectionalParticleWidth=linkDirectionalParticleWidth, linkDirectionalParticleColor=linkDirectionalParticleColor, linkDirectionalParticleResolution=linkDirectionalParticleResolution, emitParticle=emitParticle, rendererConfig=rendererConfig, pauseAnimation=pauseAnimation, resumeAnimation=resumeAnimation, centerAt=centerAt, zoom=zoom, zoomToFit=zoomToFit, cameraPosition=cameraPosition, refresh=refresh, numDimensions=numDimensions, forceEngine=forceEngine, dagMode=dagMode, dagModeOn=dagModeOn, dagLevelDistance=dagLevelDistance, dagNodeIds=dagNodeIds, ngraphPhysics=ngraphPhysics, warmupTicks=warmupTicks, cooldownTicks=cooldownTicks, cooldownTime=cooldownTime, linkHoverPrecision=linkHoverPrecision, controlType=controlType, enableNodeDrag=enableNodeDrag, getGraphBbox=getGraphBbox, heightRatio=heightRatio, size=size, active=active, nodeURL=nodeURL, useNodeImg=useNodeImg, nodeImg=nodeImg, useNodeIcon=useNodeIcon, nodeIcon=nodeIcon, nodeIcon_fontsheets=nodeIcon_fontsheets, linkId=linkId, interactive=interactive, nodeZoomId=nodeZoomId, sortRelsBy1=sortRelsBy1, sortRelsBy2=sortRelsBy2, sortRoleplayersBy1=sortRoleplayersBy1, sortRoleplayersBy2=sortRoleplayersBy2, sortRels1Descend=sortRels1Descend, sortRels2Descend=sortRels2Descend, sortRoleplayers1Descend=sortRoleplayers1Descend, sortRoleplayers2Descend=sortRoleplayers2Descend, nodesSelected=nodesSelected, nodeIdsHighlight=nodeIdsHighlight, nodeIdsVisible=nodeIdsVisible, linkIdsHighlight=linkIdsHighlight, linkIdsVisible=linkIdsVisible, externalobject_source=externalobject_source, externalobject_input=externalobject_input, centreCoordinates=centreCoordinates, useCoordinates=useCoordinates, pixelUnitRatio=pixelUnitRatio, showCoordinates=showCoordinates, gravity=gravity, maxDepth_neighbours_select=maxDepth_neighbours_select)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'Graph2D',
        namespace = 'dash_react_force_graph',
        propNames = c('id', 'graphData', 'nodeId', 'linkSource', 'linkTarget', 'backgroundColor', 'showNavInfo', 'nodeRelSize', 'nodeVal', 'nodeLabel', 'nodeDesc', 'nodeColor', 'nodeAutoColorBy', 'nodeOpacity', 'nodeResolution', 'linkLabel', 'linkDesc', 'linkColor', 'linkAutoColorBy', 'linkOpacity', 'linkLineDash', 'linkWidth', 'linkResolution', 'linkCurvature', 'linkCurveRotation', 'linkDirectionalArrowLength', 'linkDirectionalArrowColor', 'linkDirectionalArrowRelPos', 'linkDirectionalArrowResolution', 'linkDirectionalParticles', 'linkDirectionalParticleSpeed', 'linkDirectionalParticleWidth', 'linkDirectionalParticleColor', 'linkDirectionalParticleResolution', 'emitParticle', 'rendererConfig', 'pauseAnimation', 'resumeAnimation', 'centerAt', 'zoom', 'zoomToFit', 'cameraPosition', 'refresh', 'numDimensions', 'forceEngine', 'dagMode', 'dagModeOn', 'dagLevelDistance', 'dagNodeIds', 'ngraphPhysics', 'warmupTicks', 'cooldownTicks', 'cooldownTime', 'linkHoverPrecision', 'controlType', 'enableNodeDrag', 'getGraphBbox', 'heightRatio', 'size', 'active', 'nodeURL', 'useNodeImg', 'nodeImg', 'useNodeIcon', 'nodeIcon', 'nodeIcon_fontsheets', 'linkId', 'interactive', 'nodeZoomId', 'sortRelsBy1', 'sortRelsBy2', 'sortRoleplayersBy1', 'sortRoleplayersBy2', 'sortRels1Descend', 'sortRels2Descend', 'sortRoleplayers1Descend', 'sortRoleplayers2Descend', 'nodesSelected', 'nodeIdsHighlight', 'nodeIdsVisible', 'linkIdsHighlight', 'linkIdsVisible', 'externalobject_source', 'externalobject_input', 'centreCoordinates', 'useCoordinates', 'pixelUnitRatio', 'showCoordinates', 'gravity', 'maxDepth_neighbours_select'),
        package = 'dashReactForceGraph'
        )

    structure(component, class = c('dash_component', 'list'))
}
